# mamba env update --file environment.yml --prune

name: cascade
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytest            # for testing
  - pytest-cov        # for testing
  - pyyaml
  - jax
  - jupyter
  - pip:
    - colored>=2.2    # for colored printing in terminal 
