name: cascade
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytest            # for testing
  - pytest-cov        # for testing
  - numpy
  - pyyaml
  - scipy             
  - jupyter           # for notebooks
  - jax
  - matplotlib
  - pip:
    - colored>=2.2    # for colored printing in terminal 
