services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plain-cluster-gateway
    hostname: gateway
    ports:
      - "2221:22"
      - "15355:15355"
    volumes:
      - shared:/shared
    networks:
      - plain-cluster

  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plain-cluster-main
    hostname: main
    volumes:
      - shared:/shared
    networks:
      - plain-cluster

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plain-cluster-worker1
    hostname: worker1
    volumes:
      - shared:/shared
    networks:
      - plain-cluster

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plain-cluster-worker2
    hostname: worker2
    volumes:
      - shared:/shared
    networks:
      - plain-cluster

volumes:
  shared: {}

networks:
  plain-cluster:
    name: plain-cluster
