name: CI

on:
  # Trigger the workflow manually
  workflow_dispatch: ~

  push:
    branches:
      - 'main'
      - 'develop'

  pull_request: ~

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        arch_type: ["macos-ARM64", "linux-x86"]
        python_version: ["3.11", "3.12", "3.13", "3.14"]
    runs-on: "${{ fromJSON('{\"linux-x86\": [\"self-hosted\", \"Linux\", \"platform-builder-Rocky-8.6\"], \"macos-ARM64\": [\"self-hosted\", \"macOS\", \"ARM64\"]}')[matrix.arch_type] }}"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      # NOTE if setup uv used, make sure to configure uv cache correctly, to not fill home. But should be already installed and configured
      # - uses: astral-sh/setup-uv@v7
      - uses: extractions/setup-just@v3
      - run: |
          echo "uv version is $(uv --version)"
          uv sync --python "${{ matrix.python_version }}"
          just fmt
          # linux hosted runners have tmp mounted with noexec or smth like that
          if [[ "${{ matrix.arch_type }}" == "linux"* ]] ; then CASCADE_VENV_ROOT=$(pwd) just val ; else just val ; fi
