name: CI # TODO rename the file in a standalone PR

on:
  # Trigger the workflow manually
  workflow_dispatch: ~

  push:
    branches:
      - 'main'
      - 'develop'

  pull_request: ~

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        arch_type: ["macos-ARM64", "linux-x86"]
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: "${{ fromJSON('{\"linux-x86\": [\"self-hosted\", \"Linux\", \"platform-builder-Rocky-8.6\"], \"macos-ARM64\": [\"self-hosted\", \"macOS\", \"ARM64\"]}')[matrix.arch_type] }}"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.19
      - uses: extractions/setup-just@v3
      - run: |
          just fmt
          just val
